"""Test generator — produces inspectable, editable test definitions from a profile.

This is the "no black boxes" layer. After profiling, DQLens writes a tests.yaml
that shows every check it will run and WHY it was generated. Users can:
- Read it to understand what DQLens is checking
- Edit thresholds or expected values
- Delete checks they don't care about
- Add custom checks by hand

The detector reads this file at runtime and uses it instead of re-deriving
checks from the raw profile.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

import yaml

from dqlens.config import get_dqlens_dir
from dqlens.models import ColumnProfile, DatabaseProfile, TableProfile


def generate_tests(profile: DatabaseProfile) -> dict[str, Any]:
    """Generate test definitions from a database profile.

    Returns a dict structure ready to be written as YAML.
    """
    tables = []
    for table in profile.tables:
        table_tests = _generate_table_tests(table)
        if table_tests["checks"]:
            tables.append(table_tests)

    return {
        "version": "1",
        "generated_from": profile.profiled_at.isoformat(),
        "schema": profile.schema_name,
        "description": (
            "Auto-generated by dqlens from database profiling. "
            "Edit freely — delete checks you don't need, adjust thresholds, "
            "or add your own. DQLens will use this file on the next run."
        ),
        "tables": tables,
    }


def _generate_table_tests(table: TableProfile) -> dict[str, Any]:
    """Generate checks for a single table."""
    checks: list[dict[str, Any]] = []

    # Row count check
    checks.append({
        "check": "row_count",
        "expect": "greater_than",
        "value": 0,
        "reason": f"Table had {table.row_count:,} rows at profile time.",
    })

    # Baseline drift check on row count
    if table.row_count > 0:
        checks.append({
            "check": "row_count_drift",
            "expect": "change_within",
            "value": 30,  # percent
            "unit": "percent",
            "reason": "Flag if row count changes more than 30% between profiles.",
        })

    # Column-level checks
    for col in table.columns:
        checks.extend(_generate_column_checks(table, col))

    # FK integrity checks
    for fk in table.foreign_keys:
        checks.append({
            "check": "fk_integrity",
            "column": fk.source_column,
            "references": f"{table.schema_name}.{fk.target_table}.{fk.target_column}",
            "expect": "no_orphans",
            "reason": (
                f"Foreign key: {fk.source_column} → "
                f"{fk.target_table}.{fk.target_column}. "
                f"Every non-null value should exist in the target table."
            ),
        })

    # Freshness check
    if table.freshness_column and table.latest_timestamp:
        checks.append({
            "check": "freshness",
            "column": table.freshness_column,
            "expect": "within",
            "value": 24,
            "unit": "hours",
            "reason": (
                f"Most recent value in {table.freshness_column} was "
                f"{table.latest_timestamp.isoformat()}. "
                f"Flag if data becomes stale."
            ),
        })

    return {
        "table": f"{table.schema_name}.{table.table_name}",
        "row_count_at_profile": table.row_count,
        "checks": checks,
    }


def _generate_column_checks(
    table: TableProfile, col: ColumnProfile
) -> list[dict[str, Any]]:
    """Generate checks for a single column."""
    checks: list[dict[str, Any]] = []

    # Not-null check
    if col.null_count == 0 and col.row_count > 0:
        checks.append({
            "check": "not_null",
            "column": col.name,
            "reason": f"Column was 100% non-null at profile time ({col.row_count:,} rows).",
        })
    elif col.row_count > 0 and col.null_count < col.row_count:
        # Has some nulls — track the rate for drift
        checks.append({
            "check": "null_rate",
            "column": col.name,
            "expect": "below",
            "value": round(min(col.null_pct * 2, 100), 1),  # 2x current rate as threshold
            "unit": "percent",
            "baseline": col.null_pct,
            "reason": (
                f"Column had {col.null_pct}% nulls ({col.null_count:,} of "
                f"{col.row_count:,} rows). Threshold set at 2x baseline. "
                f"Adjust if this rate is expected."
            ),
        })
    elif col.null_count == col.row_count and col.row_count > 0:
        checks.append({
            "check": "all_null",
            "column": col.name,
            "severity": "medium",
            "reason": "Column is 100% null. Flag as potential dead column.",
        })

    # Uniqueness check
    if col.is_unique and col.row_count > 0:
        label = "primary key" if col.is_primary_key else "unique"
        checks.append({
            "check": "unique",
            "column": col.name,
            "reason": f"Column is {label} ({col.distinct_count:,} distinct values across {col.row_count:,} rows).",
        })

    # Pattern check
    if col.detected_pattern and col.pattern_match_pct:
        checks.append({
            "check": "pattern",
            "column": col.name,
            "pattern": col.detected_pattern,
            "expect": "match_above",
            "value": round(max(col.pattern_match_pct - 5, 50), 1),  # 5pp below current
            "unit": "percent",
            "current_match": col.pattern_match_pct,
            "reason": (
                f"Detected {col.detected_pattern} pattern with "
                f"{col.pattern_match_pct}% match rate. "
                f"Threshold set 5pp below current rate."
            ),
        })

    # Value range checks for numeric columns
    if col.min_value is not None and col.max_value is not None:
        # Check for columns that should be positive
        positive_indicators = {
            "price", "amount", "cost", "total", "quantity",
            "count", "size", "age", "weight",
        }
        col_lower = col.name.lower()
        if any(ind in col_lower for ind in positive_indicators):
            checks.append({
                "check": "positive_values",
                "column": col.name,
                "expect": "min_above",
                "value": 0,
                "current_min": col.min_value,
                "current_max": col.max_value,
                "reason": (
                    f"Column name '{col.name}' suggests positive values. "
                    f"Current range: [{col.min_value}, {col.max_value}]."
                ),
            })

    return checks


def save_tests(
    tests: dict[str, Any],
    base_path: str | Path | None = None,
) -> Path:
    """Save generated tests to .dqlens/tests.yaml."""
    dqlens_dir = get_dqlens_dir(base_path)
    dqlens_dir.mkdir(parents=True, exist_ok=True)

    filepath = dqlens_dir / "tests.yaml"
    with open(filepath, "w") as f:
        yaml.dump(
            tests, f,
            default_flow_style=False,
            sort_keys=False,
            allow_unicode=True,
            width=120,
        )
    return filepath


def load_tests(base_path: str | Path | None = None) -> dict[str, Any] | None:
    """Load tests from .dqlens/tests.yaml.

    Returns None if no tests file exists.
    """
    filepath = get_dqlens_dir(base_path) / "tests.yaml"
    if not filepath.exists():
        return None
    with open(filepath) as f:
        return yaml.safe_load(f)
